team:
  name: CLC QE
  framework: cypress
  repositories:
    automation: clc-ui
    automation_path: /Users/ashafi/Documents/work/automation/clc-ui
    feature_repos:
    - cluster-curator-controller
    - lifecycle-apis
    - acm-apis
test_environment:
  cluster_config_path: /Users/ashafi/Documents/work/ai/ai-test-gen/intelligent-test-framework/06-reference/kubeconfigs/qe6.kubeconfig
  acm_namespace: open-cluster-management
  hub_url: ''
  validation_commands:
  - oc get pods -n open-cluster-management
  - oc get clustercurator
  - oc get managedclusters
frameworks:
  cypress:
    test_directory: cypress/tests
    spec_pattern: '**/*.spec.js'
    page_objects: cypress/views
    utilities: cypress/support
    fixtures: cypress/fixtures
    commands:
      run_tests: npm run test
      lint: npm run lint:check
      format: npm run format
  selenium:
    test_directory: src/test/java
    spec_pattern: '**/*Test.java'
    page_objects: src/main/java/pages
    utilities: src/main/java/utils
    data: src/test/resources
    commands:
      run_tests: mvn test
      lint: mvn checkstyle:check
      format: mvn spotless:apply
  playwright:
    test_directory: tests
    spec_pattern: '**/*.spec.ts'
    page_objects: pages
    utilities: utils
    fixtures: fixtures
    commands:
      run_tests: npx playwright test
      lint: npm run lint
      format: npm run format
ai_prompts:
  analysis_depth: comprehensive
  test_coverage: exhaustive
  validation_rigor: production
  include_implementation_details: true
  include_customer_context: true
  include_integration_points: true
validation:
  test_plan_requirements:
  - Comprehensive feature coverage
  - Clear validation points
  - Environment considerations
  - Edge cases and error handling
  - Integration test scenarios
  implementation_requirements:
  - Production-ready code quality
  - Proper error handling
  - Clear documentation
  - Framework best practices
  - Maintainable test structure
integration:
  existing_test_patterns: true
  code_style_matching: true
  framework_conventions: true
  team_specific_utilities: true
