apiVersion: cluster.open-cluster-management.io/v1beta1
kind: ClusterCurator
metadata:
  name: sample-curator
  namespace: managed-cluster-1
spec:
  desiredCuration: upgrade
  upgrade:
    desiredUpdate: "4.15.10"
    channel: "stable-4.15"
