apiVersion: local.storage.openshift.io/v1alpha1
kind: LocalVolumeSet
metadata:
  name: my-wiped-lvset
  namespace: openshift-local-storage
spec:
  storageClassName: my-wiped-sc
  volumeMode: Block
  # <--- THIS IS THE MAGIC
  forceWipeDevicesAndDestroyAllData: true

  # For ODF typically "type: FullDeployment" uses deviceTypes= [disk].
  deviceInclusionSpec:
    deviceTypes:
    - disk

  # Make sure nodeSelector covers the worker nodes you want to wipe
  nodeSelector:
    nodeSelectorTerms:
      - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - worker-0-0
              - worker-0-1
              - worker-0-2
