apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-proxy-config
data:
  nginx.conf: |
    # This config is for TCP stream proxying only
    user nginx;
    worker_processes auto;
    pid /run/nginx.pid;

    events {
        worker_connections 1024;
    }

    stream {
        upstream spoke_api_server {
            # The destination: your spoke's internal API server IP
            server 10.1.158.150:6443;
        }

        server {
            # Listen on port 6443 on all network interfaces of the node
            listen 6443;

            # Forward traffic to the upstream destination
            proxy_pass spoke_api_server;
            proxy_connect_timeout 10s;
            proxy_timeout 10m; 
        }
    }
