apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy-deployment
  # If your ConfigMap is in a specific namespace, uncomment and set it here:
  # namespace: default
spec:
  replicas: 1 # We only want one instance of this proxy
  selector:
    matchLabels:
      app: nginx-proxy # This label links the Deployment to its Pods
  template: # This is the blueprint for the Pods the Deployment will create
    metadata:
      labels:
        app: nginx-proxy # Pods will get this label
    spec:
      # Ensure the proxy pod always runs on worker-0-0
      nodeSelector:
        kubernetes.io/hostname: worker-0-0
      # Use the node's network stack directly
      hostNetwork: true
      containers:
      - name: nginx-proxy-container
        image: nginx:1.27 # Same NGINX image
        ports:
        # This port is informational when hostNetwork=true, but good practice
        - containerPort: 6443
          name: tcp-proxy
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/nginx.conf # Mount the nginx.conf file
          subPath: nginx.conf # From the 'nginx.conf' key in the ConfigMap
      volumes:
      - name: nginx-config-volume
        configMap:
          # Must match the name of your ConfigMap
          name: nginx-proxy-config
