apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-clc-kv-proxy-conf # Specific name for clc-kv spoke
  namespace: spoke-api-proxy
data:
  nginx.conf: |
    pid /tmp/nginx.pid; # <-- ADD THIS LINE
    worker_processes auto;

    events {
        worker_connections 1024; # Adjust if needed for higher load
    }

    stream {
        upstream rhov_spoke_api_clc_kv { # Unique upstream name
            # IP and Port of the RHOV Spoke (clc-kv) API server
            server 10.1.158.150:6443;
        }

        server {
            listen 6443; # Nginx listens on this port inside its pod
            proxy_pass rhov_spoke_api_clc_kv;
            proxy_connect_timeout 10s;
            proxy_timeout 5m; # Adjust as needed for long API calls
        }
    }
