team:
  name: "ACM Selenium QE"
  framework: "selenium"
  repositories:
    automation: "acm-selenium-tests"
    automation_path: "/path/to/acm-selenium-tests"
    feature_repos: 
      - "cluster-curator-controller"
      - "multicloud-operators"
      - "registration-operator"

test_environment:
  cluster_config_path: "/path/to/kubeconfig"
  acm_namespace: "open-cluster-management"
  hub_url: "https://console-openshift-console.apps.cluster.example.com"
  validation_commands:
    - "oc get pods -n open-cluster-management"
    - "oc get clustercurator"
    - "oc get managedclusters"
    - "oc get klusterletaddonconfig"

frameworks:
  selenium:
    test_directory: "src/test/java"
    spec_pattern: "**/*Test.java"
    page_objects: "src/main/java/pages"
    utilities: "src/main/java/utils"
    data: "src/test/resources"
    commands:
      run_tests: "mvn test"
      lint: "mvn checkstyle:check"
      format: "mvn spotless:apply"
    
    selenium_config:
      browser: "chrome"
      headless: true
      timeout: 30
      wait_strategy: "explicit"
      page_load_timeout: 60

ai_prompts:
  analysis_depth: "comprehensive"
  test_coverage: "exhaustive"
  validation_rigor: "production"
  include_implementation_details: true
  include_customer_context: true
  include_integration_points: true
  selenium_specific:
    focus_on_page_objects: true
    include_waits_and_timeouts: true
    cross_browser_considerations: true

validation:
  test_plan_requirements:
    - "Cross-browser compatibility coverage"
    - "Page object model structure"
    - "Explicit wait strategies"
    - "Data-driven test scenarios"
    - "Selenium Grid compatibility"
  
  implementation_requirements:
    - "WebDriver best practices"
    - "Page factory patterns"
    - "TestNG/JUnit annotations"
    - "Maven/Gradle integration"
    - "CI/CD pipeline compatibility"

integration:
  existing_test_patterns: true
  code_style_matching: true
  framework_conventions: true
  team_specific_utilities: true
  maven_dependencies: true