[app]
name = "z-stream-analysis"
version = "1.0.0"

[notifications]
enabled = true
sound = true
persist = true

# Claude Code Hook Configuration
[hooks]
# Notification hooks
response_complete = ".claude/hooks.sh response-complete"
analysis_complete = ".claude/hooks.sh analysis-complete"  
error_occurred = ".claude/hooks.sh error"
query_submitted = ".claude/hooks.sh query-submitted"

# Comprehensive logging hooks  
before_tool_execution = ".claude/logging/comprehensive_logging_hook.py --stage pre-tool"
after_tool_execution = ".claude/logging/comprehensive_logging_hook.py --stage post-tool"
on_analysis_start = ".claude/logging/comprehensive_logging_hook.py --stage analysis-start"
on_service_start = ".claude/logging/comprehensive_logging_hook.py --stage service-start" 
on_service_complete = ".claude/logging/comprehensive_logging_hook.py --stage service-complete"

[hooks.settings]
enabled = true
timeout = 5000
background = true
shell = "/bin/bash"

[audio]
enabled = true
volume = 0.7
sounds = {
    default = "/System/Library/Sounds/Glass.aiff",
    success = "/System/Library/Sounds/Hero.aiff", 
    error = "/System/Library/Sounds/Sosumi.aiff"
}

[persistence]
save_settings = true
load_on_startup = true
session_independent = true