[notifications]
enabled = true
sound = true
volume = "medium"
events = ["ai_response_complete", "analysis_complete", "error_occurred"]

[notifications.ai_response_complete]
enabled = true
sound_file = "default"
description = "Notification when AI finishes responding to user queries"

[notifications.analysis_complete] 
enabled = true
sound_file = "success"
description = "Notification when Jenkins pipeline analysis completes"

[notifications.error_occurred]
enabled = true  
sound_file = "error"
description = "Notification when errors occur during analysis"

[app]
name = "z-stream-analysis"
persist_settings = true
auto_load_settings = true

[audio]
enabled = true
volume = 0.7
sound_type = "system"

[ui]
show_notifications = true
position = "top-right"
auto_hide = true
hide_delay = 3000